export const migrationTable: [string, string][] = [
  ['add-contact', 'person-add'],
  ['aistars', 'stars'],
  ['attachment', 'paper-clip'],
  ['avatar', 'person'],
  ['birthday', 'gift'],
  ['blog', 'newspaper'],
  ['bullet', 'dot'],
  ['calendar-day', 'calendar-date'],
  ['check-success', 'check-circle'],
  ['config', 'gear'],
  ['dashboard', 'columns'],
  ['delete', 'trash'],
  ['dislike', 'hand-thumbs-down'],
  ['edit', 'pencil'],
  ['energy', 'lightning'],
  ['external-link', 'box-arrow-up-right'],
  ['eye-closed', 'eye-slash'],
  ['home', 'house'],
  ['hourglass-full', 'hourglass-top'],
  ['idea', 'light-bulb'],
  ['like', 'hand-thumbs-up'],
  ['login', 'box-arrow-in-right'],
  ['logout', 'box-arrow-right'],
  ['mail', 'envelope'],
  ['minus', 'dash'],
  ['minus-circle', 'dash-circle'],
  ['money', 'cash'],
  ['more-horizontal', 'three-dots'],
  ['more-vertical', 'three-dots-vertical'],
  ['note', '*'],
  ['order-by', 'arrow-down-up'],
  ['profile-view', 'person-v-card'],
  ['qr-scan', 'qr-code-scan'],
  ['send-message', 'send'],
  ['share-ios', 'share'],
  ['sign', 'pen'],
  ['smile', 'emoji-smile'],
  ['success', 'check'],
  ['suitcase / suitcase-2', 'briefcase'],
  ['verified', 'security-check'],
  ['warning', 'alert'],
  ['website / public', 'globe']
]
