name: CI
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  ci:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Prepare
        run: yarn install
      
      - name: Test
        run: yarn test
      
      - name: Build
        run: yarn build:sprite
      
      - name: Build
        run: yarn build:font
      
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: yarn semantic-release