name: CI
on:
  push:
    branches: main
    paths-ignore:
      - "docs/**"
      - "tests/**"
      - ".github/**"
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Prepare
        run: yarn install
      
      - name: Test
        run: yarn test
      
      - name: Build
        run: yarn build:sprite
      
      - name: Build
        run: yarn build:font
      
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: yarn semantic-release
  
  slack_notify_success:
    needs: 
      - ci
    if: |
      needs.ci.result == 'success'
    uses: occmundial/ppr-gha-pipelines/.github/workflows/slack-notification-success.yaml@main
    secrets:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}

  slack_notify_failed:
    needs: 
      - ci
    if: |
      always() && needs.ci.result == 'failure'
    uses: occmundial/ppr-gha-pipelines/.github/workflows/slack-notification-failed.yaml@main
    secrets:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}